// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(NewMovieContext))]
    partial class NewMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Science Fiction",
                            Director = "Joseph Kosinski",
                            Edited = false,
                            LentTo = "Nathan Anderson",
                            Notes = "Favorite Movie",
                            Rating = "PG-13",
                            Title = "Tron Legacy",
                            Year = 2012
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Science Fiction",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "Joey Tate",
                            Notes = "Mind Blowing",
                            Rating = "PG-13",
                            Title = "Tenet",
                            Year = 2020
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Science Fiction",
                            Director = "Christopher Nolan",
                            Edited = true,
                            LentTo = "Tyler Nelson",
                            Notes = "Best Space Movie",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2012
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
